sudo: required

language: python
python:
  - "3.6"

services:
  - docker

env:
  - LIBRARY=annoy
  - LIBRARY=dolphinn
  - LIBRARY=faiss
  - LIBRARY=flann
  - LIBRARY=kgraph
  - LIBRARY=mrpt
  - LIBRARY=nearpy
  - LIBRARY=ngt
  - LIBRARY=nmslib
  - LIBRARY=hnswlib
  - LIBRARY=panns
  - LIBRARY=pynndescent
  - LIBRARY=rpforest
  - LIBRARY=sklearn

before_install:
  - pip install -r requirements.txt
  - python install.py

script:
  - python run.py --algorithm annoy --dataset glove-25-angular
  - python plot.py --dataset glove-25-angular --output plot.png
  - python -m unittest test/test-metrics.py
  - python create_website.py --outputdir . --scatter --latex
deploy:
  provider: releases
  api_key:
    secure: 834d0b3a98e2273d8f0be8e51cd211aaa2bb5f1e
  file: 
    - results/glove-25-angular.png
  skip_cleanup: true
  on:
    repo: VaibhavN007/ann-benchmarks
    tags: true