sudo: required

language: python
python:
  - "3.6"

services:
  - docker

env:
  - LIBRARY=kgraph

before_install:
  - pip install -r requirements.txt
  - python install.py
before_script:
  - git config --global user.email "vaibhavnit007@gmail.com"
  - git config --global user.name "VaibhavN007"
after_success:
  - ./upload-images.sh
script:
  - python run.py --algorithm kgraph --dataset mnist-784-euclidean
  - python plot.py --dataset mnist-784-euclidean --output plot.png
  - python -m unittest test/test-metrics.py
  - python create_website.py --outputdir . --scatter --latex