sudo: required

language: python
python:
  - "3.6"

services:
  - docker

env:
  # - LIBRARY=annoy
  # - LIBRARY=dolphinn
  # - LIBRARY=faiss
  # - LIBRARY=flann
  - LIBRARY=kgraph
  # - LIBRARY=mrpt
  # - LIBRARY=nearpy
  # - LIBRARY=ngt
  # - LIBRARY=nmslib
  # - LIBRARY=hnswlib
  # - LIBRARY=panns
  # - LIBRARY=pynndescent
  # - LIBRARY=rpforest
  # - LIBRARY=sklearn

before_install:
  - pip install -r requirements.txt
  - python install.py

script:
  # - python run.py --docker-tag ann-benchmarks-${LIBRARY} --max-n-algorithms 5 --dataset sign-language-digits --run-disabled
  - python run.py --algorithm kgraph --dataset sign-language-digits
  - python plot.py --dataset sign-language-digits --output plot.png
  - python -m unittest test/test-metrics.py
  - python create_website.py --outputdir . --scatter --latex
after_success:
  - chmod 777 upload-images.sh
  - bash upload-images.sh